name: Docker

on:
  schedule:
    - cron: "15 14 * * *"
  push:
    branches: ["test-ci"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-cli:
    uses: korewaChino/actions/.github/workflows/docker.yml@cappy/dist-multiarch
    with:
      publish: ${{ github.event_name != 'pull_request' }}
      dockerfile: cli.Dockerfile
      image_name: ${{ github.repository }}-cli
      artifact_name: digests-cli
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

  docker:
    uses: korewaChino/actions/.github/workflows/docker.yml@cappy/dist-multiarch
    with:
      publish: ${{ github.event_name != 'pull_request' }}
      artifact_name: digests-app
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
